version: '3.1'
services:
  apache:
    build: apache
    links:
      - mariadb
    ports:
      - 80:80
    volumes:
      - ./symfony/:/var/www/html/
  mariadb:
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
    image: mariadb:10.2.11
    ports:
      - 3306:3306